Feature/vacationmodule
klisowska-wlog/wlog_tracker pull request #12
Opened 2021-08-18 09:02 UTC by Pumbakos

- Create vacatoin db model
- Create GET endpoint that returns all vacations from db
- Create GET endpoint to return data for specific vacation based on user id
- Create POST endpoint allowing to add new vacation
- Create PUT endpoint to update specific vacation
- Create DELETE endpoint to hard delete last vacation
- Create unit tests for all user endpoints
- Change user db model to be compatible with vacation

2021-08-18 11:51 UTC, ArchitectHorrors commented on src/main/java/wlog_tracker/taskmodule/services/TaskService.java
> +                    if (field.getName().equals("id")){
Uwzględnij jeszcze warianty "Id", "iD" i "ID" tak dla bezpieczeństwa

2021-08-18 11:51 UTC, ArchitectHorrors commented on src/main/java/wlog_tracker/vacationmodule/model/Vacation.java
> +    @JsonFormat(pattern = "MMM dd, yyyy, HH:mm:ss a z")
tutaj dodaj sobie tą klasę DateFormat jak ja, wtedy będziesz musiał w razie problemów zmieniać kod w obrębie jednej linijki, a nie szukać po całym modelu

2021-08-18 11:53 UTC, Pumbakos commented on src/main/java/wlog_tracker/taskmodule/services/TaskService.java
> +                    if (field.getName().equals("id")){
To może wrzucę po prostu equasIgnoreCase()

2021-08-18 11:54 UTC, Pumbakos commented on src/main/java/wlog_tracker/vacationmodule/model/Vacation.java
> +    @JsonFormat(pattern = "MMM dd, yyyy, HH:mm:ss a z")
Jak zrobisz PR to zaciągnę od Ciebie i zrobię mały refactor żeby nie robić merge konfliktów

2021-08-18 11:55 UTC, ArchitectHorrors commented on src/main/java/wlog_tracker/taskmodule/services/TaskService.java
> +                    if (field.getName().equals("id")){
Tak zrób

2021-08-19 07:19 UTC, Pumbakos commented on src/main/java/wlog_tracker/taskmodule/services/TaskService.java
> +                    if (field.getName().equals("id")){
Done

2021-08-20 08:38 UTC, klisowska-wlog requested changes

2021-08-20 08:38 UTC, klisowska-wlog commented on .gitignore
> +src/main/resources/application.properties
czemu app properties do ignore dodany?

2021-08-20 12:18 UTC, merged