Feature/usermodule
klisowska-wlog/wlog_tracker pull request #7
Opened 2021-08-06 07:57 UTC by Pumbakos

-add SwaggerAPI and SwaggerUI
-add tests for User
-refactor '/update'
-User: change String-type 'title' field to Title-type

2021-08-06 13:54 UTC, klisowska-wlog requested changes

2021-08-06 13:54 UTC, klisowska-wlog commented on src/main/java/wlog_tracker/usermodule/User.java
>          boolean allowUpdate = false;
ta zmienna bardziej sprawdza czy sie dane zupdateowaly, wiec nazwa troche myli. Moze lepiej zmienic na isUpdated

2021-08-06 13:54 UTC, klisowska-wlog commented on src/main/java/wlog_tracker/usermodule/User.java
> +    public boolean updateProperties(User user){
tutaj funkcje sprobuj przerobic na generyczne przelatywanie po atrybutach
Pytanie czy w ogole jest nam taka metoda potrzebna do czegokolwiek

2021-08-06 13:54 UTC, klisowska-wlog commented on src/main/java/wlog_tracker/usermodule/User.java
> +    public boolean copyAllProperties(User user) {
to samo jak z update - czy jest ta metoda konieczna?

2021-08-06 13:54 UTC, klisowska-wlog commented on src/main/java/wlog_tracker/usermodule/UserController.java
> +    public HttpStatus update(@RequestBody User user, @PathVariable(name = "id") Long id) {
zamiast zwracac HttpStatus mozemy zwracac Usera (jezeli update sie poprawnie wykonal), w przeciwnym przypadku null np albo rzucic w ogole exception

2021-08-06 13:54 UTC, klisowska-wlog commented on src/test/java/wlog_tracker/usermodule/UserTest.java
> +        copyFrom.setName("Testowy");
zamiast wywolywac tutaj settery poszczegolne, lepiej bedzie zrobic klase ktora zrobi to za nas - np jakis TestUtils i wewnatrz tworzyc te obiekty testowe

2021-08-06 13:54 UTC, klisowska-wlog commented on src/test/java/wlog_tracker/usermodule/UserTest.java
> +    public void copyProperUserWithoutSurname(){
nie ma potrzeby robienia testow w kazdym wariancie - jezeli koniecznie metoda copy i update maja byc utrzymane to wystarcza po 2 testy - jeden pozytywny (czyli kopiujemy i potwierdzamy wartosci), i drugi w ktorym np podajemy blanki do kopiowania i asertujemy czy rzeczywiscie dostajemy efekt jaki chcemy)

2021-08-09 07:59 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserTest.java
> +    public void copyProperUserWithoutSurname(){
Done

2021-08-09 08:00 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserTest.java
> +        copyFrom.setName("Testowy");
Done

2021-08-09 08:00 UTC, Pumbakos commented on src/main/java/wlog_tracker/usermodule/UserController.java
> +    public HttpStatus update(@RequestBody User user, @PathVariable(name = "id") Long id) {
Done

2021-08-09 08:00 UTC, Pumbakos commented on src/main/java/wlog_tracker/usermodule/User.java
>          boolean allowUpdate = false;
Done

2021-08-09 08:04 UTC, Pumbakos commented on src/main/java/wlog_tracker/usermodule/User.java
> +    public boolean updateProperties(User user){
Wg mnie jest, mówimy o updateProperties(User user), bo sprawdzamy wewnątrz czy dane nie są nulem, bo raczej nie chcemy aktualizować z jakiejś wartości na null? Czy pozostawiamy taką możliwość?

2021-08-09 08:05 UTC, Pumbakos commented on src/main/java/wlog_tracker/usermodule/User.java
> +    public boolean copyAllProperties(User user) {
Rzeczywiście metoda była zbędna i usunąłem ją

2021-08-09 09:15 UTC, klisowska-wlog requested changes

2021-08-09 09:15 UTC, klisowska-wlog commented on src/main/java/wlog_tracker/usermodule/User.java
> +@ToString(exclude = {"id"})
testowales to? dziala?

2021-08-09 09:15 UTC, klisowska-wlog commented on src/test/java/wlog_tracker/usermodule/UserGenerator.java
> +    private User user = new User();
klasa wyglada fajnie, tylko jeszcze zamiast uzywac tutaj wewnetrznego atrybutu, to bezposrednio bym zwracala utworzonego usera w metodzie

2021-08-09 09:38 UTC, Pumbakos commented on src/main/java/wlog_tracker/usermodule/User.java
> +@ToString(exclude = {"id"})
To mi wyrzuca: 
User(name=Simon, surname=Smithowsky, imageUrl=pl.pumbakos, pesel=49480599895, title=project manager)

2021-08-09 09:40 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserGenerator.java
> +    private User user = new User();
Done

2021-08-09 10:25 UTC, ArchitectHorrors commented on src/main/java/wlog_tracker/usermodule/UserController.java
> +    public boolean delete(@PathVariable(name = "id") Long id){
musi zwracać Usera/ null

2021-08-09 11:54 UTC, Pumbakos commented on src/main/java/wlog_tracker/usermodule/UserController.java
> +    public boolean delete(@PathVariable(name = "id") Long id){
Done

2021-08-09 12:56 UTC, klisowska-wlog approved these changes

2021-08-09 12:57 UTC, ArchitectHorrors approved these changes

2021-08-09 12:57 UTC, merged