Create unit tests for all user endpoints
klisowska-wlog/wlog_tracker pull request #8
Opened 2021-08-09 13:12 UTC by Pumbakos

2021-08-09 13:57 UTC, ArchitectHorrors commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User user2 = new UserGenerator().createUser("Dennis", "Civilowsky",
ja to miałem wykładane na studiach przez prof. Bałchanowskiego, żeby w nazwach zmiennych nie używać cyfr. Reszta teamu bardziej się połapie jak ustawisz "userForTests" np.

2021-08-09 13:57 UTC, ArchitectHorrors commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User user2 = new UserGenerator().createCompleteUser();
Same - user2

2021-08-09 13:57 UTC, ArchitectHorrors commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User user2 = new UserGenerator().createBlankUser();
Same - user2

2021-08-09 13:57 UTC, ArchitectHorrors commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User user2 = new UserGenerator().createEmptyValuesUser();
Same - user2

2021-08-09 14:38 UTC, klisowska-wlog requested changes

2021-08-09 15:04 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User request = new UserGenerator().createUser("Testowy", "Palowsky",
Masz rację, po pisaniu testów się mi udzieliło 😆

2021-08-10 09:49 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +    private User user = new UserGenerator().createCompleteUser();
User został przeniesiony, ale jeśli chodzi o GsonJsonProvider i ObjectMapper to wykrzacza jak dodaję mu @Autowired, @MockBean albo @Mock

2021-08-10 10:15 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User user2 = new UserGenerator().createUser("Dennis", "Civilowsky",
Done

2021-08-10 10:15 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User user2 = new UserGenerator().createCompleteUser();
Done

2021-08-10 10:15 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User user2 = new UserGenerator().createBlankUser();
Done

2021-08-10 10:15 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        User user2 = new UserGenerator().createEmptyValuesUser();
Done

2021-08-10 11:47 UTC, klisowska-wlog commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        String json = gsonJsonProvider.toJson(Arrays.asList(completeUser, additionalCompleteUser));
tutaj jeszcze drobna uwaga - zarowno tutaj jak i w deklaracji Mockito tworzysz nowa tablice tych userow. 
Tak czysto optymalizacyjnie lepiej jest ja stworzyc raz w zmiennej i ta zmienna uzyc w obu miejscach - unikamy wtedy podwojnego tworzenia listy o takich samych wartosciach

2021-08-10 11:47 UTC, klisowska-wlog commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +    @DisplayName("Send DELETE with proper values under /user")
opis lekko do poprawy :)

2021-08-10 12:10 UTC, Pumbakos commented on src/test/java/wlog_tracker/usermodule/UserControllerTest.java
> +        String json = gsonJsonProvider.toJson(Arrays.asList(completeUser, additionalCompleteUser));
Done

2021-08-10 12:34 UTC, klisowska-wlog approved these changes

2021-08-10 13:23 UTC, ArchitectHorrors approved these changes

2021-08-10 13:24 UTC, merged